---
version: '3.9'
services:
  freqtrade-bybit:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade-bybit
    volumes:
      - "./user_data:/freqtrade/user_data"
    environment:
      - TZ=Asia/Taipei
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "0.0.0.0:8085:8080"

    # Default command used when running `docker compose up`
    # command: >
    #   trade
    #   --logfile /freqtrade/user_data/logs/freqtrade.log
    #   --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
    #   --config /freqtrade/user_data/config.json
    #   --config /freqtrade/user_data/config.private.json
    #   --strategy SampleStrategy

    # Command to run NostalgiaForInfinityX strategy
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade-bybit.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-bybit.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config-bybit.private.json
      --config /freqtrade/user_data/strategies/NostalgiaForInfinityX/pairlist-volume-bybit-usdt.json
      --config /freqtrade/user_data/strategies/NostalgiaForInfinityX/blacklist-bybit.json
      --strategy NostalgiaForInfinityX4
